version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:latest
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: server --console-address ":9001" http://minio-node-0{1...4}.buu.ac.th/disk
    volumes:
      - /var/disk:/disk
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    #logging:
    #  driver: syslog
    #  options:
    #    syslog-address: "tcp://127.0.0.1:514"
    #    tag: "minio"
    network_mode: "host"
