version: '3.8'
services:
  minio:
    hostname: minio
    image: quay.io/minio/minio:latest
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: changeme
      MINIO_ROOT_PASSWORD: changeme
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: server --console-address ":9001" http://minio{1...4}/disk
    volumes:
      - minio-data:/disk
volumes:
  minio-data:
